### ISSUE TITLE
Needs search capability

### ISSUE THREAD

**Issue by yarikoptic** [dandi/handbook#105]
ATM I do not see any way to search besides geeky "go to github, search in the source"

![image](https://github.com/dandi/handbook/assets/39889/efdec65f-f5a6-40b8-a9a5-54fa0d2fe50b)

**Comment by kabilar** [comment]
Hi @yarikoptic, #103 should address this issue.  Thank you.

**Comment by kabilar** [comment]
Fixed in #103.
