### ISSUE TITLE
Provide explicit guidance/expectations for zarr uploads

### ISSUE THREAD

**Issue by aaronkanzer** [dandi/handbook#110]
Zarr uploads still remain in `Draft` mode, as they are yet to be versioned. 

Our handbook does not provide documentation for "what to expect" for Zarr uploads in the DANDI ecosystem. (e.g. https://github.com/dandi/handbook/blob/master/docs/13_upload.md does not contain any reference)

The goal of this Issue is to capture follow-up work to communicate the Zarr workflow correctly in this handbook, `dandi-cli` and `dandi-archive`

Relates to https://github.com/dandi/dandi-archive/issues/1811

**Comment by kabilar** [comment]
Thank you @aaronkanzer.  I will update the handbook to describe the user flow for Dandisets with Zarr assets.
