### ISSUE TITLE
usability notes

### ISSUE THREAD

**Issue by bendichter** [dandi/handbook#22]
In Uploading a Dandiset, Setup:
* Provide screenshot of where the API key is
* Add link to instructions for Python virtualenv
* Change to simply “pip install -U dandi”

In Uploading, Data upload/management workflow:
* “New Dataset” -> “NEW DANDISET” even better, show a picture of this button inline in the instructions
* “Reach out to us for help” should link to github helpdesk chooser in new window
* Add instructions for non-NWB files, break it into NWB and non-NWB
    * In NWB-specific subsection, make sure you have an updated version of pynwb
    * If you have having trouble with validation, make sure conversions were run with the most recent version of PyNWB and MatNWB

In download section,
> 1.	Downloading a Dandiset.
> 2.	Downloading a subject.
> 3.	Downloading a file.

needs to be expanded out

**Comment by djarecka** [comment]
@bendichter 0 in #23:


> In Uploading a Dandiset, Setup:
> 
> * Provide screenshot of where the API key is

the description were to find the key was already there (after merging lost content), let me know if you still want the screenshot

> * Add link to instructions for Python virtualenv

done
> * Change to simply “pip install -U dandi”
done
> 
> In Uploading, Data upload/management workflow:
> 
> * “New Dataset” -> “NEW DANDISET” even better, show a picture of this button inline in the instructions

changed (without adding picture)
> * “Reach out to us for help” should link to github helpdesk chooser in new window

done
> * Add instructions for non-NWB files, break it into NWB and non-NWB

wasn't sure what should be added to the non-NWB section, haven't done it
>   
>   * In NWB-specific subsection, make sure you have an updated version of pynwb
>   * If you have having trouble with validation, make sure conversions were run with the most recent version of PyNWB and MatNWB

added 

> 
> In download section,
> 
> > 1. Downloading a Dandiset.
> > 2. Downloading a subject.
> > 3. Downloading a file.
> 
> needs to be expanded out

the lost content had examples, etc.

**Comment by melster1010** [comment]
@bendichter @djarecka 
We're trying to clean up the Handbook issues, looks like a lot of this was addressed, can it be closed? Thanks!

**Comment by djarecka** [comment]
yes, looks like I tried to address most of the suggestions, if @bendichter doesn't have any comments I believe we can close. Thank you!
