### ISSUE TITLE
add NWB best practices section

### ISSUE THREAD

**Issue by satra** [dandi/handbook#42]
@bendichter - given some of the issues being discussed with the biccn datasets, i realized that there is no information in the handbook on the dandi extension or how to add such info. also slice/tissue info would be relevant to ophys as well and perhaps the term ndx-dandi-icephys may semantically be confusing. 

it would be nice to have a clear section in the handbook on pointers to dandi related nwb.

**Comment by bendichter** [comment]
We're working on incorporating this information into the core schema, as we think this will create a smoother using experience and this is a frequently requested feature.

**Comment by satra** [comment]
@bendichter - i suspect core changes will take time. in the short term is this now incorporated into nwb inspector? if so can this issue be closed?

**Comment by CodyCBakerPhD** [comment]
@satra There is indeed now a link to the current NWB Best Practices in the DANDI handbook ('uploading' section): https://github.com/dandi/handbook/blob/master/docs/13_upload.md?plain=1#L59

It also looks like the corresponding issue tracking the `icephys` addition to the NWB Inspector was completed: https://github.com/NeurodataWithoutBorders/nwbinspector/issues/103

**Comment by satra** [comment]
thanks @CodyCBakerPhD
