### ISSUE TITLE
add clearer descriptions of the archive

### ISSUE THREAD

**Issue by satra** [dandi/handbook#43]
based on the questions below, it would be useful for us to create a page in the handbook that directly addresses this.

questions from priyanka subhash at USC

- Data storage - Cloud-based platform; user must upload data through Github
Type of data - The archive accepts cellular neurophysiology data including electrophysiology, optophysiology, and behavioral time-series, and images from immunostaining experiments
- Data collection - User must create a DANDI account, create a Python environment, install the DANDI CLI into Python environment, register a dandiset to generate an identifier, convert data to NWB
- Data maintenance - Data is maintained on Github platform
- Data Upload Process - User must create a DANDI account, create a Python environment, install the DANDI CLI into Python environment, register a dandiset to generate an identifier, convert data to NWB
- Data access - A Github account is required to access/download public datasets and to be given access to private datasets through DANDI
- Data download - Using the Web application - Each Dandiset has a View Data option. This provides a folder-like view to navigate a Dandiset. Any file in the Dandiset has a download icon next to it. You can click this icon to download a file to your device where you are browsing or right click to get the download URL of the file. You can then use this URL programmatically or in other applications such as the NWB Explorer or in a Jupyter notebook on Dandihub. Using the Python CLI - Install Python client using DANDI code
- Accepted Data File Formats - NWB, BIDS, NDM
- In-house analytical tools - Dandihub provides a Jupyter environment to interact with the DANDI archive. To use the hub, you will need to register an account using the DANDI Web application. Please note that Dandihub is not intended for significant computation, but provides a place to introspect Dandisets and files.

**Comment by satra** [comment]
@djarecka - i will help, but can you start a PR with a page listing the above? some of the info is not quite right and each bullet should go to a relevant section of the handbook for more details.

**Comment by djarecka** [comment]
ok, will start

**Comment by djarecka** [comment]
just for the references:

Dandiset Actions:

- Data View
- Data Download
- Data Upload
- Data Publish

More details about the actions:

* Data View
    - use DANDI Archive to search public Dandisets
    - check the Dandiset landing page for more information: authors, resources, data metadata, funding

* Data Download
    - find the Dandiset: see Dandi View
    - install DANDI CLI in your python environment
    - use DANDI CLI to download the Dandiset (check the `Download` button on the landing page for the specific command)

* Data Upload
    - create a GitHub account if you don't have one
    - create a DANDI Archive account using the GitHub login
    - register a new Dandiset and generate the Dandiset identifier
    - convert data to NWB if needed
    - install DANDI CLI in your python environment
    - use DANDI CLI to upload files to the DANDI Archive
    - edit Metadata information in the DANDI Archive website

* Data Publish
   - upload your data to the DANDI Archive: see Data Upload
   - be sure to provide all required Metadata fields
   - publish the Dandiset and create a specific version for the Dandiset

**Comment by satra** [comment]
this has been addressed in several PRs
