### ISSUE TITLE
Handbook 1st pass

### ISSUE THREAD

**Issue by melster1010** [dandi/handbook#44]
perform thorough copyedit based on the style sheet guidelines

**Comment by waxlamp** [comment]
@melster1010, can you confirm whether this has been done?

**Comment by melster1010** [comment]
Yes I had it all but merged before the pause, now I see that Satra merged
it and other work has been done on the handbook in the meantime. I've been
busy with a half dozen SBIR/STTR proposals all due this week, so after
Wednesday I'll have to see where the handbook is at!
