### ISSUE TITLE
Review and edit README files

### ISSUE THREAD

**Issue by melster1010** [dandi/handbook#74]
- [x] Edit the READMEs for style consistency/grammar/etc
  - [x] dandi-archive (overall readme and web app readme)  https://github.com/dandi/dandi-archive/pull/1386
  - [x] dandi-cli https://github.com/dandi/dandi-cli/pull/1170
  - [x] dandi-hub  https://github.com/dandi/dandi-hub/pull/50
  - [x] helpdesk https://github.com/dandi/helpdesk/pull/87
  - [x] dandi-schema https://github.com/dandi/dandi-schema/pull/152
- [x] Determine and implement a common structure where applicable

**Comment by waxlamp** [comment]
@melster1010, could you please edit the description of this issue to list out which READMEs remain to edit? We can better track progress of this issue that way. Thanks!
