### ISSUE TITLE
favicon not showing up

### ISSUE THREAD

**Issue by bendichter** [dandi/handbook#80]
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/844306/224834995-5bdca4a5-1753-47c0-aad4-325930a01002.png">

The favicon is not working for me

**Comment by satra** [comment]
it's showing up for me in incognito mode, so i suspect it may be a caching issue.

**Comment by bendichter** [comment]
Not for me

<img width="518" alt="image" src="https://user-images.githubusercontent.com/844306/224851521-32ec66f0-9873-4e2c-8729-b53d5bf9f4dc.png">

**Comment by bendichter** [comment]
I also tried hard refreshing

**Comment by satra** [comment]
not seeing it myself. anything in the console? i have tried both arc and safari in different modes.

**Comment by bendichter** [comment]
<img width="546" alt="image" src="https://user-images.githubusercontent.com/844306/224854556-66066544-6d45-4823-b0b7-fe266383149c.png">

nothing of note in the console.

It's not showing up in Safari for me

<img width="640" alt="image" src="https://user-images.githubusercontent.com/844306/224854732-4a22ecee-84dc-489a-9e28-d7c1c7fba81e.png">


Is the favicon showing up for anyone else? It might just be an issue with my computer.

**Comment by satra** [comment]
sorry i didn't realize which repo this was. should show up soon when it builds.
