### ISSUE TITLE
Document specific requirements for upload of NWB files

### ISSUE THREAD

**Issue by rly** [dandi/handbook#81]
DANDI requires certain metadata to be present in an NWB file for upload. This is checked using the nwbinspector with the dandi config. However, these requirements are not documented besides looking at:
https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/src/nwbinspector/internal_configs/dandi.inspector_config.yaml

Can these requirements be documented in the DANDI handbook?

**Comment by waxlamp** [comment]
@bendichter and @melster1010: can the two of you meet to discuss what such a handbook page would look like?

My own (speculative) thoughts: describe briefly NWB and its significant role in DANDI; describe the inspector and how it works; describe the minimum requirements enforced by the above-linked config file; finally, describe how the user can run the inspector themselves if they wish (so they can pre-approve their files before uploading).

**Comment by melster1010** [comment]
test

**Comment by melster1010** [comment]
Hi Ben,
I'm happy to meet any day this week if you'd like, re: this handbook issue
that came up last week.
Thanks,
~ Mary Elise

**Comment by bendichter** [comment]
@melster1010 The main requirements would be:

* A Subject is required.
* The subject must have a subject_id, species, sex, and either date_of_birth or age.
* The species must be in Latin binomial, e.g. "Mus musculus".
* The sex must be "M", "F", "O", or "U".
* The age, if present, must in in ISO 8601 format, e.g. "P70D" for 70 days, or, if it is a range, should be "[lower]/[upper]", e.g. "P10W/P12W", which would mean "between 10 and 12 weeks."

This is formally defined by [this file](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/src/nwbinspector/internal_configs/dandi.inspector_config.yaml), which specifies which NWB Inspector checks are critical for DANDI.

I'd be happy to meet to discuss any questions and iron out details. Feel free to grab a spot on [my calendly](calendly.com/ben-dichter).

**Comment by melster1010** [comment]
resolved with PR #85
