### ISSUE TITLE
Brain link in handbook should link back to top level

### ISSUE THREAD

**Issue by waxlamp** [dandi/handbook#86]
There's a brain image in the handbook page which is just a link to the top level *of the handbook*; I expected this link to take me back to the dandiarchive home page.

**Comment by kabilar** [comment]
Hi @waxlamp, are you referring to the icon in the top left of the header shown below (red arrow)?

![image](https://github.com/dandi/handbook/assets/871137/517f373b-4ac6-4708-97f8-340fd5d28ff2)


 If so, I can change it to link back to https://dandiarchive.org using the configuration described in these [docs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo).

(Perhaps in the long run it would be nice to have the same header across the various sites [dandiarchive.org, www.dandiarchive.org, www.dandiarchive.org/handbook, etc.])

**Comment by kabilar** [comment]
Fixed in #108
