### ISSUE TITLE
refactor docs for creating an account

### ISSUE THREAD

**Issue by bendichter** [dandi/handbook#92]
We currently have docs for creating an account [here](https://www.dandiarchive.org/handbook/13_upload/#create-an-account-on-dandi) within the section for creating and uploading Dandisets. This is not ideal, because a user may want to create an account in order to access DANDI Hub to analyze existing data, and such a user might find it difficult to find this section. I think it would be better to have a separate section on signing up for DANDI that is linked to by the section for creating and uploading Dandisets as well as the section on the DANDI Hub. This section should also explain when a DANDI login is necessary and when it is not (i.e. if all you want to do is download data)

**Comment by kabilar** [comment]
Fixed in #108
